---
description: >
  ArtiVC (Artifact Version Control) is a version control system for large files.
images:
  - "ArtiVC_workspace.png"

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/InfuseAI/ArtiVC
geekdocEditPath: edit/main/docs

geekdocSearch: true
geekdocSearchShowParent: true

geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

geekdocImageLazyLoading: true
geekdocDarkModeDim: true
