name: Go test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run test
      run: make test
      
  it-test-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run test
      run: make integration-test
      env:
        TEST_REPOSITORY: ${{ secrets.REPOSITORY_S3 }} 
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}      
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      